# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  vulcan-agent:
    image: wazuh/wazuh-agent:4.14.3
    hostname: vulcan-agent
    restart: always
    environment:
      - WAZUH_MANAGER_SERVER=<WAZUH_MANAGER_IP>
      - WAZUH_AGENT_NAME=vulcan-agent
    volumes:
      - ./config/wazuh-agent-conf:/wazuh-config-mount/etc/ossec.conf
